# Generated by Django 4.1.2 on 2022-10-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='data',
            field=models.DateTimeField(default=0),
        ),
    ]
