# Generated by Django 4.1.2 on 2022-10-23 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_articles_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 23, 19, 11, 51, 379432)),
        ),
    ]
